### ISSUE TITLE
show menu items in navbar in desktop mode

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/proximap#14]
https://github.com/mmmatthew/proximap/blob/e84debe8069d9199b7e8d131cdcd207addaf39eb/code/src/app/navbar/navbar.component.html#L27

use media query in css to show or hide group

**Comment by axel105** [comment]
https://github.com/mmmatthew/proximap/blob/e84debe8069d9199b7e8d131cdcd207addaf39eb/code/src/app/navbar/navbar.component.html#L27
