### ISSUE TITLE
in componentDetails flag whether there is a dog/cattle bucket

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/proximap#43]
see also https://www.wikidata.org/wiki/Wikidata:Property_proposal/animal_water_well

**Comment by mmmatthew** [comment]
this was planned anyway

**Comment by ralfhauser** [comment]
WP3, item 3a

**Comment by mmmatthew** [comment]
fixed with https://github.com/mmmatthew/proximap/commit/baaded56638bc1b2eed5495777d095040efc0b74

**Comment by ralfhauser** [comment]
see also https://taginfo.openstreetmap.org/keys/wetap%3Adog#overview

(so far, doesn't seem to be used significantly)

see also https://github.com/water-fountains/proximap/issues/118
