### ISSUE TITLE
enhance letsencrypt to serve also include as alternate www.water-fountains.org and not just water-fountains.org

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/proximap#47]
recent chrome and Firefox block access to https://www.water-fountains.org   :(

If difficult, Christian can certainly help you

**Comment by mmmatthew** [comment]
Can he do it? I don't really know how.

**Comment by mmmatthew** [comment]
Thanks Christian.
I tried to do the same for beta.water-fountains.org, but was not able to authenticate the change.
`certbot certonly --cert-name beta.water-fountains.org -beta.water-fountains.org,www.beta.water-fountains.org`
