### ISSUE TITLE
Name of fountain shown in details, but not overview ?

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/proximap#48]
![image](https://user-images.githubusercontent.com/1681677/42689955-cbb8732c-86a2-11e8-95be-16d96714e5d6.png)

**Comment by ralfhauser** [comment]
Just checked https://www.wikidata.org/wiki/Q55171079  and the labels in EN and DE were empty.
I added the name manually.
Shouldn't the wikidata import set at least the DE label if none is present so far ?

**Comment by mmmatthew** [comment]
Most fountains in the WVZ dataset do not have a name associated to them. That is probably the reason why none is defined. If a “bezeichnung” is defined, it is saved in the German label.

**Comment by mmmatthew** [comment]
fixed with https://github.com/mmmatthew/proximap/commit/b4320afb5fa5dff3b72c57a7423005227e8b1986
