### ISSUE TITLE
slow detail window opening

### ISSUE THREAD

**Issue by ralfhauser** [mmmatthew/proximap#60]
on 2MB download line (0.4MB upload), opening a detail (e.g. of Venedig) today was very slow. First I thought we need thumbnails, but the pictures delivered were small - what could be the reason for this slow pop-up ?

**Comment by mmmatthew** [comment]
The reason probably lies with the wikidata server, which sometimes needs a
lot of time for simple queries. This should be fixed when we switch the app
to use cached query results.
-- 


Matthew

**Comment by ralfhauser** [comment]
Thx for the hypothesis - what is the ETA for the "cached query results" ?

But I am still confused why I mostly saw this over this slow connection and less when on a quick connection

**Comment by mmmatthew** [comment]
The datablue server already does caching for complete city query results,
but the app data handler still needs to be adapted. It is on my list for
this week.
-- 


Matthew
